<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBuBGhPM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBuBGhPM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBuBGhPM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBuBGhPM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBuBGhPM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BuBGhPM',
    'container.build_id' => 'fba82d97',
    'container.build_time' => 1588168286,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBuBGhPM');
