<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container74qmVuL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container74qmVuL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container74qmVuL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container74qmVuL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container74qmVuL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '74qmVuL',
    'container.build_id' => '2cfcc992',
    'container.build_time' => 1588084218,
], __DIR__.\DIRECTORY_SEPARATOR.'Container74qmVuL');
