<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUZUexpQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUZUexpQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUZUexpQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUZUexpQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUZUexpQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UZUexpQ',
    'container.build_id' => 'dfbe99f6',
    'container.build_time' => 1587990369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUZUexpQ');
